apiVersion: apps/v1
kind: Deployment
metadata:
  name: leonardo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leonardo-api
  template:
    metadata:
      labels:
        app: leonardo-api
    spec:
      containers:
        - name: leonardo-api
          image: us-docker.pkg.dev/cit-262-418012/leonardo-api/api-tests # IMAGE NEEDS TO BE ARTIFACT REGISTRY NEW REPOSITORY
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10